imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'PageBundle:Admin:form.html.twig' #'A2lixTranslationFormBundle::form.html.twig' #'::form.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
            ApplicationSonataUserBundle: ~
            SonataUserBundle: ~
            FOSUserBundle: ~ 

# Stof Doctrine Extensions (Translatable)
stof_doctrine_extensions:
    default_locale: ca
    translation_fallback: true
    orm:
        default:
            translatable: true
            sluggable: true

# a2Lix Sonata Translations
a2lix_translation_form:
    locales: [ es, en ]

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:      { type: memory }

# Sonata Admin
sonata_admin:
    title:  'iona iona · administrador de continguts'
    title_logo: '/favicon.png'
    templates:
        layout: PageBundle:Admin:standard_layout_tinymce.html.twig
        dashboard: PageBundle:Admin:my_dashboard.html.twig
        ajax: SonataAdminBundle::ajax_layout.html.twig
        list: SonataAdminBundle:CRUD:list.html.twig
        show: SonataAdminBundle:CRUD:show.html.twig
        edit: FluxPageBundle:Admin:edit.html.twig # antes SonataAdminBundle:CRUD:edit.html.twig en un update de Sonata salta un error en este recurso (linea 35)
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            Pàgines:
            Bloc:
            Productes:
            Botiga:

# Sonata Block
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

# Sonata FOS User
sonata_user:
    security_acl: true
    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
        group:           
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

# Friends Of Symfony (FOS)
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

# Genemu Form Select 2 Bundle
genemu_form:
    select2: ~
    date: ~

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        # simple: ~
        simple:   # original theme "advanced"
            plugins:
                - "advlist autolink lists link charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime nonbreaking save contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "undo redo | styleselect | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | print preview"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

# Vich Uploader Bundle
vich_uploader:
    db_driver: orm
    mappings:
        imatge:
            uri_prefix: /uploads/images
            upload_destination: %kernel.root_dir%/../web/uploads/images
            inject_on_load: false
            delete_on_remove: true
        documents:
            uri_prefix: /uploads/documents
            upload_destination: %kernel.root_dir%/../web/uploads/documents
            inject_on_load: false
            delete_on_remove: true

# Liip Imagine Bundle            
liip_imagine:
    cache_prefix: /uploads/cache
    filter_sets:
        imatge60x60:
            quality: 90
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        imatge80:
            quality: 90
            filters:
                thumbnail: { size: [80, null], mode: outbound }
        imatge220:
            quality: 90
            filters:
                thumbnail: { size: [220, null], mode: outbound }
        imatge260:
            quality: 90
            filters:
                thumbnail: { size: [260, null], mode: outbound }
        imatge530:
            quality: 80
            filters:
                thumbnail: { size: [530, null], mode: outbound }
        imatge600:
            quality: 80
            filters:
                thumbnail: { size: [600, null], mode: outbound }
        imatge814:
            quality: 80
            filters:
                thumbnail: { size: [814, null], mode: outbound }
        imatge940:
            quality: 80
            filters:
                thumbnail: { size: [940, null], mode: outbound }

# DIC config
services:
    flux.admin.page:
        class: Flux\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pàgines, label: Pàgina }
        arguments: [null, Flux\PageBundle\Entity\Page, FluxPageBundle:PageAdmin]
    flux.admin.category:
        class: Flux\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Productes, label: Categoria }
        arguments: [null, Flux\ProductBundle\Entity\Category, FluxProductBundle:CategoryAdmin]
    flux.admin.product:
        class: Flux\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Productes, label: Producte }
        arguments: [null, Flux\ProductBundle\Entity\Product, FluxProductBundle:ProductAdmin]
    flux.admin.blog.category:
            class: Flux\BlogBundle\Admin\CategoryAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Bloc, label: Categoria }
            arguments: [null, Flux\BlogBundle\Entity\Category, FluxBlogBundle:CategoryAdmin]
    flux.admin.blog.post:
                class: Flux\BlogBundle\Admin\PostAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: Bloc, label: Article }
                arguments: [null, Flux\BlogBundle\Entity\Post, FluxBlogBundle:PostAdmin]
    ionaiona.admin.store:
            class: IonaIona\PageBundle\Admin\StoreCustomerAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Botiga, label: Client }
            arguments: [null, IonaIona\PageBundle\Entity\StoreCustomer, PageBundle:StoreCustomerAdmin]
    ionaiona.admin.shopping:
                class: IonaIona\PageBundle\Admin\StoreCustomerProductAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: Botiga, label: Compra }
                arguments: [null, IonaIona\PageBundle\Entity\StoreCustomerProduct, PageBundle:StoreCustomerProductAdmin]