home_ca:
    pattern:        /{_locale}/inici/
    defaults:       { _controller: PageBundle:Default:home }
    requirements:
        _locale:    ca

home_es:
    pattern:        /{_locale}/inicio/
    defaults:       { _controller: PageBundle:Default:home }
    requirements:
        _locale:    es

home_en:
    pattern:        /{_locale}/home/
    defaults:       { _controller: PageBundle:Default:home }
    requirements:
        _locale:    en

############################ ARMARI
armari_ca:
    pattern:        /{_locale}/l-armari/
    defaults:       { _controller: PageBundle:Default:armari }
    requirements:
        _locale:    ca

armari_es:
    pattern:        /{_locale}/armario/
    defaults:       { _controller: PageBundle:Default:armari }
    requirements:
        _locale:    es

armari_en:
    pattern:        /{_locale}/wardrobe/
    defaults:       { _controller: PageBundle:Default:armari }
    requirements:
        _locale:    en

armari_balena_ca:
    pattern:        /{_locale}/l-armari/balena
    defaults:       { _controller: PageBundle:Armari:balena }
    requirements:
        _locale:    ca

armari_balena_es:
    pattern:        /{_locale}/armario/ballena
    defaults:       { _controller: PageBundle:Armari:balena }
    requirements:
        _locale:    es

armari_balena_en:
    pattern:        /{_locale}/wardrobe/whale
    defaults:       { _controller: PageBundle:Armari:balena }
    requirements:
        _locale:    en

armari_girafa_ca:
    pattern:        /{_locale}/l-armari/girafa
    defaults:       { _controller: PageBundle:Armari:girafa }
    requirements:
        _locale:    ca

armari_girafa_es:
    pattern:        /{_locale}/armario/jirafa
    defaults:       { _controller: PageBundle:Armari:girafa }
    requirements:
        _locale:    es

armari_girafa_en:
    pattern:        /{_locale}/wardrobe/giraffe
    defaults:       { _controller: PageBundle:Armari:girafa }
    requirements:
        _locale:    en

armari_gossalsitxa_ca:
    pattern:        /{_locale}/l-armari/gos-salsitxa
    defaults:       { _controller: PageBundle:Armari:gossalsitxa }
    requirements:
        _locale:    ca

armari_gossalsitxa_es:
    pattern:        /{_locale}/armario/perro-salchicha
    defaults:       { _controller: PageBundle:Armari:gossalsitxa }
    requirements:
        _locale:    es

armari_gossalsitxa_en:
    pattern:        /{_locale}/wardrobe/dachshund
    defaults:       { _controller: PageBundle:Armari:gossalsitxa }
    requirements:
        _locale:    en

armari_pitet_ca:
    pattern:        /{_locale}/l-armari/pitet
    defaults:       { _controller: PageBundle:Armari:pitet }
    requirements:
        _locale:    ca

armari_pitet_es:
    pattern:        /{_locale}/armario/babero
    defaults:       { _controller: PageBundle:Armari:pitet }
    requirements:
        _locale:    es

armari_pitet_en:
    pattern:        /{_locale}/wardrobe/bib
    defaults:       { _controller: PageBundle:Armari:pitet }
    requirements:
        _locale:    en

armari_ocell_ca:
    pattern:        /{_locale}/l-armari/ocell
    defaults:       { _controller: PageBundle:Armari:ocell }
    requirements:
        _locale:    ca

armari_ocell_es:
    pattern:        /{_locale}/armario/pajaro
    defaults:       { _controller: PageBundle:Armari:ocell }
    requirements:
        _locale:    es

armari_ocell_en:
    pattern:        /{_locale}/wardrobe/bird
    defaults:       { _controller: PageBundle:Armari:ocell }
    requirements:
        _locale:    en

armari_banderola_ca:
    pattern:        /{_locale}/l-armari/banderola
    defaults:       { _controller: PageBundle:Armari:banderola }
    requirements:
        _locale:    ca

armari_banderola_es:
    pattern:        /{_locale}/armario/banderola
    defaults:       { _controller: PageBundle:Armari:banderola }
    requirements:
        _locale:    es

armari_banderola_en:
    pattern:        /{_locale}/wardrobe/flag
    defaults:       { _controller: PageBundle:Armari:banderola }
    requirements:
        _locale:    en

armari_items_ca:
    pattern:        /{_locale}/l-armari/{nom}/{id}
    defaults:       { _controller: PageBundle:Armari:items }
    requirements:
        _locale:    ca

armari_items_es:
    pattern:        /{_locale}/armario/{nom}/{id}
    defaults:       { _controller: PageBundle:Armari:items }
    requirements:
        _locale:    es

armari_items_en:
    pattern:        /{_locale}/wardrobe/{nom}/{id}
    defaults:       { _controller: PageBundle:Armari:items }
    requirements:
        _locale:    en

############################ TALLER
taller_ca:
    pattern:        /{_locale}/taller/
    defaults:       { _controller: PageBundle:Default:taller }
    requirements:
        _locale:    ca

taller_es:
    pattern:        /{_locale}/taller/
    defaults:       { _controller: PageBundle:Default:taller }
    requirements:
        _locale:    es

taller_en:
    pattern:        /{_locale}/workshop/
    defaults:       { _controller: PageBundle:Default:taller }
    requirements:
        _locale:    en

taller_historia_ca:
    pattern:        /{_locale}/taller/historia
    defaults:       { _controller: PageBundle:Taller:historia }
    requirements:
        _locale:    ca

taller_historia_es:
    pattern:        /{_locale}/taller/historia
    defaults:       { _controller: PageBundle:Taller:historia }
    requirements:
        _locale:    es

taller_historia_en:
    pattern:        /{_locale}/workshop/history
    defaults:       { _controller: PageBundle:Taller:historia }
    requirements:
        _locale:    en

taller_artesania_ca:
    pattern:        /{_locale}/taller/artesania
    defaults:       { _controller: PageBundle:Taller:artesania }
    requirements:
        _locale:    ca

taller_artesania_es:
    pattern:        /{_locale}/taller/artesania
    defaults:       { _controller: PageBundle:Taller:artesania }
    requirements:
        _locale:    es

taller_artesania_en:
    pattern:        /{_locale}/workshop/crafts
    defaults:       { _controller: PageBundle:Taller:artesania }
    requirements:
        _locale:    en

taller_proximitat_ca:
    pattern:        /{_locale}/taller/proximitat
    defaults:       { _controller: PageBundle:Taller:proximitat }
    requirements:
        _locale:    ca

taller_proximitat_es:
    pattern:        /{_locale}/taller/proximidad
    defaults:       { _controller: PageBundle:Taller:proximitat }
    requirements:
        _locale:    es

taller_proximitat_en:
    pattern:        /{_locale}/workshop/proximity
    defaults:       { _controller: PageBundle:Taller:proximitat }
    requirements:
        _locale:    en

############################ DIARI
diari_ca:
    pattern:        /{_locale}/el-diari/
    defaults:       { _controller: PageBundle:Default:diari }
    requirements:
        _locale:    ca

diari_es:
    pattern:        /{_locale}/diario/
    defaults:       { _controller: PageBundle:Default:diari }
    requirements:
        _locale:    es

diari_en:
    pattern:        /{_locale}/newspaper/
    defaults:       { _controller: PageBundle:Default:diari }
    requirements:
        _locale:    en

############################ BOTIGA
buy_step_1_ca:
    pattern:        /{_locale}/botiga/{id}
    defaults:       { _controller: PageBundle:Botiga:step1 }
    requirements:
        _locale:    ca

buy_step_1_es:
    pattern:        /{_locale}/tienda/{id}
    defaults:       { _controller: PageBundle:Botiga:step1 }
    requirements:
        _locale:    es

buy_step_1_en:
    pattern:        /{_locale}/shop/{id}
    defaults:       { _controller: PageBundle:Botiga:step1 }
    requirements:
        _locale:    en

cancel_buy_ca:
    pattern:        /{_locale}/botiga/eliminar/{id}
    defaults:       { _controller: PageBundle:Botiga:remove }
    requirements:
        _locale:    ca

cancel_buy_es:
    pattern:        /{_locale}/botiga/borrar/{id}
    defaults:       { _controller: PageBundle:Botiga:remove }
    requirements:
        _locale:    es

cancel_buy_en:
    pattern:        /{_locale}/botiga/remove/{id}
    defaults:       { _controller: PageBundle:Botiga:remove }
    requirements:
        _locale:    en

############################ GLOBAL
inicial:
    pattern:        /
    defaults:       { _controller: PageBundle:Default:home }
