<?php 
namespace IonaIona\PageBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

use Flux\ProductBundle\Entity\Category;
use Flux\ProductBundle\Entity\Translation\CategoryTranslation;
use Flux\ProductBundle\Entity\Product;
use Flux\ProductBundle\Entity\Translation\ProductTranslation;

class Categories implements FixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $category = new Category();
        $category->setCode('00A-00A');
        $category->setTitle('balena');
        $category->setPosition(1);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('ballena');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('whale');
        $category->addTranslation($translation);
        $manager->persist($category);

        $product = new Product();
        $product->setCategory($category);
        $product->setCode('BAL001');
        $product->setName('Balena la Pepa');
        $product->setBirth('Amposta');
        $product->setDimensions('100 cm');
        $product->setWeight(200);
        $product->setFabrics(4);
        $product->setSpecifications('100% cotó orgànic');
        $product->setImage1('whale1.png');
        $product->setPrice(35);
        $product->setStock(1);
        $product->setPosition(1);
        $product->setIsActive(true);
        $translation = new ProductTranslation();
        $translation->setLocale('es');
        $translation->setField('name');
        $translation->setContent('La ballena Pepa');
        $product->addTranslation($translation);
        $translation = new ProductTranslation();
        $translation->setLocale('en');
        $translation->setField('name');
        $translation->setContent('The whale Pepa');
        $product->addTranslation($translation);
        $manager->persist($product);

        $product = new Product();
        $product->setCategory($category);
        $product->setCode('BAL002');
        $product->setName('Balena la Buba');
        $product->setBirth('Amposta');
        $product->setDimensions('100 cm');
        $product->setWeight(200);
        $product->setFabrics(4);
        $product->setSpecifications('100% cotó orgànic');
        $product->setImage1('whale2.png');
        $product->setPrice(36);
        $product->setStock(1);
        $product->setPosition(2);
        $product->setIsActive(true);
        $translation = new ProductTranslation();
        $translation->setLocale('es');
        $translation->setField('name');
        $translation->setContent('La ballena Buba');
        $product->addTranslation($translation);
        $translation = new ProductTranslation();
        $translation->setLocale('en');
        $translation->setField('name');
        $translation->setContent('The whale Buba');
        $product->addTranslation($translation);
        $manager->persist($product);

        $product = new Product();
        $product->setCategory($category);
        $product->setCode('BAL003');
        $product->setName('Balena la Pipa');
        $product->setBirth('Amposta');
        $product->setDimensions('100 cm');
        $product->setWeight(200);
        $product->setFabrics(4);
        $product->setSpecifications('100% cotó orgànic');
        $product->setImage1('whale3.png');
        $product->setPrice(37);
        $product->setStock(1);
        $product->setPosition(3);
        $product->setIsActive(true);
        $translation = new ProductTranslation();
        $translation->setLocale('es');
        $translation->setField('name');
        $translation->setContent('La ballena Pipa');
        $product->addTranslation($translation);
        $translation = new ProductTranslation();
        $translation->setLocale('en');
        $translation->setField('name');
        $translation->setContent('The whale Pipa');
        $product->addTranslation($translation);
        $manager->persist($product);

        $product = new Product();
        $product->setCategory($category);
        $product->setCode('BAL004');
        $product->setName('Balena la Mima');
        $product->setBirth('Amposta');
        $product->setDimensions('100 cm');
        $product->setWeight(200);
        $product->setFabrics(4);
        $product->setSpecifications('100% cotó orgànic');
        $product->setImage1('whale2.png');
        $product->setPrice(38);
        $product->setStock(0);
        $product->setPosition(4);
        $product->setIsActive(true);
        $translation = new ProductTranslation();
        $translation->setLocale('es');
        $translation->setField('name');
        $translation->setContent('La ballena Mima');
        $product->addTranslation($translation);
        $translation = new ProductTranslation();
        $translation->setLocale('en');
        $translation->setField('name');
        $translation->setContent('The whale Mima');
        $product->addTranslation($translation);
        $manager->persist($product);

        $category = new Category();
        $category->setCode('00A-00B');
        $category->setTitle('girafa');
        $category->setPosition(2);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('jirafa');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('jiraffe');
        $category->addTranslation($translation);
        $manager->persist($category);

        $product = new Product();
        $product->setCategory($category);
        $product->setCode('JIR001');
        $product->setName('Jirafa la Jifa');
        $product->setBirth('Amposta');
        $product->setDimensions('50 cm');
        $product->setWeight(200);
        $product->setFabrics(4);
        $product->setSpecifications('100% cotó orgànic');
        $product->setImage1('jiraffe1.png');
        $product->setPrice(39);
        $product->setStock(1);
        $product->setPosition(1);
        $product->setIsActive(true);
        $translation = new ProductTranslation();
        $translation->setLocale('es');
        $translation->setField('name');
        $translation->setContent('La girafa Jifa');
        $product->addTranslation($translation);
        $translation = new ProductTranslation();
        $translation->setLocale('en');
        $translation->setField('name');
        $translation->setContent('The jiraffe Jifa');
        $product->addTranslation($translation);
        $manager->persist($product);

        $category = new Category();
        $category->setCode('00A-00C');
        $category->setTitle('gos salsitxa');
        $category->setPosition(3);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('perro salchicha');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('dachshund');
        $category->addTranslation($translation);
        $manager->persist($category);

        $category = new Category();
        $category->setCode('00A-00D');
        $category->setTitle('pitet');
        $category->setPosition(4);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('babero');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('bib');
        $category->addTranslation($translation);
        $manager->persist($category);

        $category = new Category();
        $category->setCode('00A-00E');
        $category->setTitle('ocell');
        $category->setPosition(5);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('pájaro');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('bird');
        $category->addTranslation($translation);
        $manager->persist($category);

        $category = new Category();
        $category->setCode('00A-00F');
        $category->setTitle('banderola');
        $category->setPosition(6);
        $category->setIsActive(true);
        $translation = new CategoryTranslation();
        $translation->setLocale('es');
        $translation->setField('title');
        $translation->setContent('banderola');
        $category->addTranslation($translation);
        $translation = new CategoryTranslation();
        $translation->setLocale('en');
        $translation->setField('title');
        $translation->setContent('flag');
        $category->addTranslation($translation);
        $manager->persist($category);

        $manager->flush();
    }
}